const colors = {
	primary: '#346afc',
	'primary-hover': '#2554d6',
	'primary-light': '#a7beff',
	'primary-bright': '#ebf3ff',
	secondary: '#ff7a7a',
	'secondary-hover': '#dd5a5a',
	'secondary-bright': '#fff2f2',
	mint: '#09dab7',
	'mint-light': '#97eace',
	'mint-bright': '#e5faf3',
	taffy: '#7e66cd',
	'taffy-light': '#a594dc',
	'taffy-bright': '#efecf9',
	sun: '#fff250',
	'sun-light': '#fff8a2',
	'sun-bright': '#fffdea',
	gray: '#6f738b',
	'gray-dark': '#4c547c',
	'gray-light': '#b5b8cc',
	'gray-bright': '#ebebff',
	white: '#ffffff',
	black: '#000000',
};

export default colors;
